[package]
name = "delete-chp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tiberius = "0.12.2"
dotenv = "0.15.0"
tokio = { version = "1.38.1", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["compat"]}